# pull official base image 
FROM python:3.9.0-slim-buster

# setting working directory
WORKDIR /usr/src/app

# set Environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

# install all needed dependencies

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy project
COPY . .